/*
Chrysalis Service API

Testing HealthCheckAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/bonjuruu/chrysalis-service-client/go-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_HealthCheckAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HealthCheckAPIService CheckHealth", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.HealthCheckAPI.CheckHealth(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
