/*
Chrysalis Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ICreateUserRequestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ICreateUserRequestDTO{}

// ICreateUserRequestDTO struct for ICreateUserRequestDTO
type ICreateUserRequestDTO struct {
	// User name.
	Username string `json:"username"`
	// User email.
	Email string `json:"email"`
}

type _ICreateUserRequestDTO ICreateUserRequestDTO

// NewICreateUserRequestDTO instantiates a new ICreateUserRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewICreateUserRequestDTO(username string, email string) *ICreateUserRequestDTO {
	this := ICreateUserRequestDTO{}
	this.Username = username
	this.Email = email
	return &this
}

// NewICreateUserRequestDTOWithDefaults instantiates a new ICreateUserRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewICreateUserRequestDTOWithDefaults() *ICreateUserRequestDTO {
	this := ICreateUserRequestDTO{}
	return &this
}

// GetUsername returns the Username field value
func (o *ICreateUserRequestDTO) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ICreateUserRequestDTO) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ICreateUserRequestDTO) SetUsername(v string) {
	o.Username = v
}

// GetEmail returns the Email field value
func (o *ICreateUserRequestDTO) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ICreateUserRequestDTO) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ICreateUserRequestDTO) SetEmail(v string) {
	o.Email = v
}

func (o ICreateUserRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ICreateUserRequestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *ICreateUserRequestDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varICreateUserRequestDTO := _ICreateUserRequestDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varICreateUserRequestDTO)

	if err != nil {
		return err
	}

	*o = ICreateUserRequestDTO(varICreateUserRequestDTO)

	return err
}

type NullableICreateUserRequestDTO struct {
	value *ICreateUserRequestDTO
	isSet bool
}

func (v NullableICreateUserRequestDTO) Get() *ICreateUserRequestDTO {
	return v.value
}

func (v *NullableICreateUserRequestDTO) Set(val *ICreateUserRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableICreateUserRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableICreateUserRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableICreateUserRequestDTO(val *ICreateUserRequestDTO) *NullableICreateUserRequestDTO {
	return &NullableICreateUserRequestDTO{value: val, isSet: true}
}

func (v NullableICreateUserRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableICreateUserRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


