/*
Chrysalis Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IUpdateUsernameRequestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IUpdateUsernameRequestDTO{}

// IUpdateUsernameRequestDTO struct for IUpdateUsernameRequestDTO
type IUpdateUsernameRequestDTO struct {
	// User name.
	Username string `json:"username"`
}

type _IUpdateUsernameRequestDTO IUpdateUsernameRequestDTO

// NewIUpdateUsernameRequestDTO instantiates a new IUpdateUsernameRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIUpdateUsernameRequestDTO(username string) *IUpdateUsernameRequestDTO {
	this := IUpdateUsernameRequestDTO{}
	this.Username = username
	return &this
}

// NewIUpdateUsernameRequestDTOWithDefaults instantiates a new IUpdateUsernameRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIUpdateUsernameRequestDTOWithDefaults() *IUpdateUsernameRequestDTO {
	this := IUpdateUsernameRequestDTO{}
	return &this
}

// GetUsername returns the Username field value
func (o *IUpdateUsernameRequestDTO) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *IUpdateUsernameRequestDTO) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *IUpdateUsernameRequestDTO) SetUsername(v string) {
	o.Username = v
}

func (o IUpdateUsernameRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IUpdateUsernameRequestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *IUpdateUsernameRequestDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIUpdateUsernameRequestDTO := _IUpdateUsernameRequestDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIUpdateUsernameRequestDTO)

	if err != nil {
		return err
	}

	*o = IUpdateUsernameRequestDTO(varIUpdateUsernameRequestDTO)

	return err
}

type NullableIUpdateUsernameRequestDTO struct {
	value *IUpdateUsernameRequestDTO
	isSet bool
}

func (v NullableIUpdateUsernameRequestDTO) Get() *IUpdateUsernameRequestDTO {
	return v.value
}

func (v *NullableIUpdateUsernameRequestDTO) Set(val *IUpdateUsernameRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableIUpdateUsernameRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableIUpdateUsernameRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIUpdateUsernameRequestDTO(val *IUpdateUsernameRequestDTO) *NullableIUpdateUsernameRequestDTO {
	return &NullableIUpdateUsernameRequestDTO{value: val, isSet: true}
}

func (v NullableIUpdateUsernameRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIUpdateUsernameRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


