/*
Chrysalis Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IPostDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPostDTO{}

// IPostDTO struct for IPostDTO
type IPostDTO struct {
	// Post id.
	Id string `json:"id"`
	// Name of the author.
	Author string `json:"author"`
	// Title of the post.
	Title string `json:"title"`
	// Content of the post.
	Content string `json:"content"`
	// URL of the post thumbnail.
	Thumbnail string `json:"thumbnail"`
	// Post creation date.
	CreatedAt string `json:"createdAt"`
	// Post update date.
	UpdatedAt string `json:"updatedAt"`
}

type _IPostDTO IPostDTO

// NewIPostDTO instantiates a new IPostDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPostDTO(id string, author string, title string, content string, thumbnail string, createdAt string, updatedAt string) *IPostDTO {
	this := IPostDTO{}
	this.Id = id
	this.Author = author
	this.Title = title
	this.Content = content
	this.Thumbnail = thumbnail
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewIPostDTOWithDefaults instantiates a new IPostDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPostDTOWithDefaults() *IPostDTO {
	this := IPostDTO{}
	return &this
}

// GetId returns the Id field value
func (o *IPostDTO) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IPostDTO) SetId(v string) {
	o.Id = v
}

// GetAuthor returns the Author field value
func (o *IPostDTO) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *IPostDTO) SetAuthor(v string) {
	o.Author = v
}

// GetTitle returns the Title field value
func (o *IPostDTO) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *IPostDTO) SetTitle(v string) {
	o.Title = v
}

// GetContent returns the Content field value
func (o *IPostDTO) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *IPostDTO) SetContent(v string) {
	o.Content = v
}

// GetThumbnail returns the Thumbnail field value
func (o *IPostDTO) GetThumbnail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetThumbnailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumbnail, true
}

// SetThumbnail sets field value
func (o *IPostDTO) SetThumbnail(v string) {
	o.Thumbnail = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IPostDTO) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IPostDTO) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *IPostDTO) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *IPostDTO) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *IPostDTO) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o IPostDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPostDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["author"] = o.Author
	toSerialize["title"] = o.Title
	toSerialize["content"] = o.Content
	toSerialize["thumbnail"] = o.Thumbnail
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *IPostDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"author",
		"title",
		"content",
		"thumbnail",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPostDTO := _IPostDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIPostDTO)

	if err != nil {
		return err
	}

	*o = IPostDTO(varIPostDTO)

	return err
}

type NullableIPostDTO struct {
	value *IPostDTO
	isSet bool
}

func (v NullableIPostDTO) Get() *IPostDTO {
	return v.value
}

func (v *NullableIPostDTO) Set(val *IPostDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableIPostDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableIPostDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPostDTO(val *IPostDTO) *NullableIPostDTO {
	return &NullableIPostDTO{value: val, isSet: true}
}

func (v NullableIPostDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPostDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


