name: Check for File Changes

on:
  pull_request:

jobs:
  check-files:
    name: Verify files are generated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install OpenAPI Generator CLI
        run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli version  # Verify installation

      - name: Run your specific command
        run: |
          make generate_clients

      - name: Check for file changes
        run: |
          git diff --exit-code || (echo "❌ openapi.yml has been modified. Please generate the openapi.yml file before merging." && exit 1)
